"""Regenerate ``REFERENCES.md`` from the benchmarks themselves.

    python examples/verification/_references.py          # rewrite REFERENCES.md
    python examples/verification/_references.py --check  # fail if it is stale

The table is generated rather than hand-maintained for two reasons: several people
(and agents) add benchmarks in parallel, and a hand-kept table is exactly the sort of
thing that drifts away from the ``Case`` objects it claims to describe. The ``Case``
is the single source of truth; this file is a view of it.

Importing a benchmark module is cheap -- the solve happens inside ``solve_at``, which
nothing here calls.
"""

from __future__ import annotations

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
OUT = HERE / "REFERENCES.md"

HEADER = """# Reference values

Every benchmark's target, and where it comes from. A row is either **computed** (the
example evaluates the closed form itself -- preferred) or **quoted** (a published
constant, which needs a real citation and an independent check).

<!-- Generated by _references.py from the Case objects. Do not edit by hand:
     run `python examples/verification/_references.py` instead. -->

| benchmark | quantity | reference | tolerance | source |
|---|---|---|---|---|
"""

FOOTER = """
## Checking a quoted constant

Quoted values are the suite's weak point: a plausible-looking wrong number produces a
benchmark that passes and verifies nothing. Each one gets an independent review pass
that re-derives or re-sources it **without** seeing the original justification.
Disagreements are resolved before the example lands, not by adjusting the tolerance.

See `README.md`, *Reference-value integrity*.
"""


def load_cases():
    sys.path.insert(0, str(HERE))
    out = []
    for path in sorted(HERE.glob("ex_*.py")):
        spec = importlib.util.spec_from_file_location(f"_ref_{path.stem}", path)
        mod = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(mod)
        except Exception as exc:                       # a broken example should not
            print(f"  !! {path.name}: {exc}", file=sys.stderr)   # block the others
            continue
        case = getattr(mod, "CASE", None)
        if case is not None:
            out.append((path.stem, case))
    return out


def render(cases):
    rows = []
    for stem, c in cases:
        rows.append(
            f"| `{stem}` | {c.quantity} | {c.reference:.6g} | {c.tolerance:.3g} | "
            f"{c.citation} |"
        )
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if REFERENCES.md is out of date")
    args = p.parse_args(argv)

    text = render(load_cases())
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print("REFERENCES.md is stale -- run python examples/verification/_references.py")
            return 1
        print("REFERENCES.md is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
